package com.tend.app

import com.tend.app.data.db.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Diffs the hand-written v2→v3 migration against the schema Room generates from
 * the entities (`app/schemas/…/3.json`, exported at build time).
 *
 * Room validates a migrated database structurally when it opens it, so one wrong
 * column type — or a missing `ON UPDATE NO ACTION` — throws "Migration didn't
 * properly handle" the first time an existing user upgrades. There is no
 * emulator in CI to catch that, and the failure only ever reproduces on a device
 * that already has v2 data. This test is the substitute: if the migration and
 * the entities disagree, it fails at `testDebugUnitTest`.
 */
class RoomSchemaTest {

    private val schemaJson: String = run {
        // Read from disk rather than the test classpath: processTestResources can
        // run before KSP writes the schema, but test *execution* always follows
        // main compilation, so the file is reliably there by now.
        val relative = "schemas/com.tend.app.data.db.AppDatabase/$SCHEMA_VERSION.json"
        val candidates = listOf(File(relative), File("app/$relative"))
        candidates.firstOrNull { it.isFile }?.readText()
            ?: error(
                "Exported Room schema not found in ${candidates.joinToString { it.absolutePath }}. " +
                    "It is generated by KSP from the room.schemaLocation arg in app/build.gradle.kts."
            )
    }

    /**
     * Every `createSql` in the exported schema, with Room's `${'$'}{TABLE_NAME}`
     * placeholder resolved.
     *
     * Deliberately parsed by regex rather than with `org.json`: that class is
     * stubbed out in JVM unit tests and would throw "not mocked". The values are
     * JSON strings containing no double quotes, so this is unambiguous.
     */
    private val exportedSql: List<String> by lazy {
        val token = Regex(""""(tableName|createSql)"\s*:\s*"([^"]*)"""")
        var currentTable = ""
        buildList {
            token.findAll(schemaJson).forEach { m ->
                val (key, value) = m.destructured
                if (key == "tableName") currentTable = value
                else add(value.replace("\${TABLE_NAME}", currentTable))
            }
        }.map(::normalize)
    }

    /** Whitespace runs differ harmlessly between Room versions; nothing else may. */
    private fun normalize(sql: String) = sql.replace(Regex("\\s+"), " ").trim()

    @Test
    fun `exported schema is at the version the code declares`() {
        assertTrue(
            "Exported schema is not version $SCHEMA_VERSION — did @Database change without a migration?",
            Regex(""""version"\s*:\s*$SCHEMA_VERSION""").containsMatchIn(schemaJson),
        )
    }

    @Test
    fun `every migration CREATE TABLE matches the generated schema`() {
        (AppDatabase.V3_TABLES + AppDatabase.V4_TABLES).forEach { assertMatches(it) }
    }

    @Test
    fun `every migration CREATE INDEX matches the generated schema`() {
        AppDatabase.V3_INDICES.forEach { assertMatches(it) }
    }

    @Test
    fun `migration creates every table the new entities declare`() {
        // Catches the other direction: an entity added to @Database but forgotten
        // in the migration, which fails only on upgrade and not on fresh install.
        val created = AppDatabase.V3_TABLES + AppDatabase.V4_TABLES
        listOf(
            "chat_threads", "chat_messages", "message_links", "attachments", "memory_entries",
        ).forEach { table ->
            assertTrue(
                "Migration is missing a CREATE TABLE for `$table`",
                created.any { it.contains("`$table`") },
            )
        }
    }

    private fun assertMatches(migrationSql: String) {
        val mine = normalize(migrationSql)
        val table = Regex("`(\\w+)`").find(mine)?.groupValues?.get(1)
        if (mine in exportedSql) return

        // Surface the closest generated statement — a raw "not found" tells you
        // nothing about which character is wrong.
        val closest = exportedSql.filter { table != null && it.contains("`$table`") }
        assertEquals(
            "Migration SQL does not match the schema Room generates for `$table`.",
            closest.joinToString("\n"),
            mine,
        )
        error("Migration SQL for `$table` has no counterpart in the exported schema:\n$mine")
    }

    private companion object {
        /** Bump alongside `@Database(version = …)`; the test then checks both. */
        const val SCHEMA_VERSION = 4
    }
}
